[package]
name = "radix-sort"
version = "0.1.0"
authors = ["hemangandhi <hemangandhi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rdxsort = "0.3.0"